"""Lattice phi^4 target: thin re-export of bijx plus MCMC reference numbers.

Action convention (stated once here and in the notebooks — no 1/2 factors,
matching ``bijx.lattice.scalar.phi4_term``):

    S(phi) = sum_x [ sum_mu (phi_{x+mu} - phi_x)^2 + m^2 phi_x^2 + lam phi_x^4 ],
    p(phi) ~ exp(-S(phi))

on a periodic L x L lattice; ``m^2 < 0`` is the broken phase.
"""

from __future__ import annotations

import jax.numpy as jnp
from bijx.lattice.scalar import phi4_term  # noqa: F401  (re-export)
from jax_autovmap import autovmap

# --------------------------------------------------------------------------
# Pinned couplings — validated empirically for the tutorial recipe.
# At L=6 these give a strongly bimodal m-histogram (wells at ~±0.85), the
# equivariant ConvVF flow (5x5 kernel + free-theory prior, see
# scripts/_phi4_common.py) reaches usable ESS in ~300 reverse-KL steps with
# a clearly two-peaked raw histogram, and the broken-Z2 variant collapses
# reproducibly at seed 0.  Deeper m² (-1.2) does not converge with the
# 300-step recipe; shallower (-0.6) makes the collapse story weak — do not
# change without re-validating convergence and the seed-0 collapse.
# --------------------------------------------------------------------------
L_DEFAULT = 6
M2 = -1.0
LAM = 0.5


@autovmap(phi=2)
def action(phi: jnp.ndarray, m2: float = M2, lam: float = LAM) -> jnp.ndarray:
    """Total phi^4 action; batched over leading axes.

    Args:
        phi: Field configuration(s), shape ``(..., L, L)``.

    Returns:
        Action value(s), shape ``(...,)``.
    """
    return jnp.sum(phi4_term(phi, m2, lam))


def magnetization(phi: jnp.ndarray) -> jnp.ndarray:
    """Magnetization per site ``m = L^-2 sum_x phi_x``; ``(..., L, L) -> (...,)``."""
    return jnp.mean(phi, axis=(-2, -1))


def binder_u4(mag: jnp.ndarray) -> jnp.ndarray:
    """Binder cumulant ``U4 = 1 - <m^4> / (3 <m^2>^2)`` from magnetization samples."""
    m2 = jnp.mean(mag**2)
    m4 = jnp.mean(mag**4)
    return 1.0 - m4 / (3.0 * m2**2)


# --------------------------------------------------------------------------
# High-precision MCMC reference numbers (with error bars), generated by
# ``scripts/hmc_phi4_reference.py`` (64 independent chains, errors from the
# cross-chain spread; jackknife over chains for U4) — never call them
# "exact enumeration"; they are a high-precision MCMC reference for
# continuous fields.  The m-histogram data for the same run lives in
# ``checkpoints/phi4_hmc_reference.npz`` (bin_edges, density).
#
# Schema: {(L, m2, lam): {"abs_mag": (value, err), "mag_sq": (value, err),
#                          "binder_u4": (value, err), "n_samples": int}}
# --------------------------------------------------------------------------
REFERENCE: dict[tuple[int, float, float], dict] = {}

REFERENCE[(6, -1.0, 0.5)] = {
    "abs_mag": (0.79091, 0.00055),
    "mag_sq": (0.64403, 0.00072),
    "binder_u4": (0.63455, 0.00022),
    "n_samples": 256000,
}
